#!/usr/bin/env python
"""Django manage.py — generated by Chartexa Pro."""
import os
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
from django.core.management import execute_from_command_line
execute_from_command_line(sys.argv)
